local Locale = {}

Locale.Current = "EN"

Locale.Strings = {
	EN = {
		APP_NAME = "VORTEX",
		APP_SUB = "COMBAT HUB",
		TAB_AIMBOT = "AIMBOT",
		TAB_VISUALS = "VISUALS",
		TAB_MOVEMENT = "MOVEMENT",
		TAB_WORLD = "WORLD",
		TAB_PROFILE = "PROFILE",
		TAB_BINDS = "BINDS",
		TAB_SETTINGS = "SETTINGS",
		MENU_KEY = "MENU KEY",
		SEC_AIMBOT = "AIMBOT",
		SEC_TRIGGER = "TRIGGER BOT",
		SEC_ESP = "ESP",
		SEC_MOVEMENT = "MOVEMENT",
		SEC_PRESETS = "PRESETS",
		SEC_RENDERING = "RENDERING",
		SEC_CAMERA = "CAMERA",
		SEC_WEATHER = "WEATHER",
		SEC_ATMOSPHERE = "ATMOSPHERE",
		SEC_TIME = "TIME",
		SEC_POSTFX = "POST FX",
		SEC_CROSSHAIR = "CROSSHAIR",
		SEC_HITFX = "HIT FEEDBACK",
		SEC_SESSION = "SESSION",
		SEC_ACCOUNT = "ACCOUNT",
		SEC_SERVER = "SERVER",
		SEC_INTERFACE = "INTERFACE",
		SEC_THEME = "THEME CUSTOMIZATION",
		SEC_CONFIG = "CONFIG",
		SEC_SCRIPT = "SCRIPT",
		SEC_LANGUAGE = "LANGUAGE",
		OPT_AIMBOT = "Aimbot",
		OPT_HOLD_RMB = "Hold Right Mouse",
		OPT_TEAMCHECK = "Team Check",
		OPT_VISIBLECHECK = "Visible Check",
		OPT_AIMPART = "Aim Part",
		OPT_AIMSPEED = "Aim Speed",
		OPT_FOVRADIUS = "FOV Radius",
		OPT_MAXDIST = "Max Distance",
		OPT_PREDICTION = "Movement Prediction",
		OPT_PREDICTIONTIME = "Prediction Time",
		OPT_SHOWFOV = "Show FOV Circle",
		OPT_TARGETLINE = "Target Line",
		OPT_TRIGGERBOT = "Trigger Bot",
		OPT_TRIGGERFOV = "Trigger FOV",
		OPT_SHOWTRIGGERFOV = "Show Trigger FOV",
		OPT_HITBOX = "Include Hitbox Size",
		OPT_TRIGGERPART = "Trigger Part",
		OPT_WALLCHECK = "Wall Check",
		OPT_ONLYAIM = "Only While Aiming (RMB)",
		OPT_REACTDELAY = "Reaction Delay",
		OPT_FIREINTERVAL = "Fire Interval",
		OPT_HUMANIZE = "Humanize Timing",
		OPT_CLICKMODE = "Click Mode",
		OPT_ESP = "ESP",
		OPT_HIDETEAM = "Hide Teammates",
		OPT_BOXES = "Boxes",
		OPT_CORNERBOXES = "Corner Boxes",
		OPT_NAMES = "Names",
		OPT_DISTANCE = "Distance",
		OPT_HEALTHBAR = "Health Bar",
		OPT_SKELETON = "Skeleton",
		OPT_HEADDOT = "Head Dot",
		OPT_WEAPON = "Weapon",
		OPT_OFFSCREEN = "Offscreen Arrows",
		OPT_CHAMS = "Chams",
		OPT_TRACERS = "Tracers",
		OPT_TRACERORIGIN = "Tracer Origin",
		OPT_ESPCOLOR = "ESP Color",
		OPT_ESPDIST = "ESP Distance",
		OPT_SPEED = "Speed",
		OPT_WALKSPEED = "Walk Speed",
		OPT_JUMPPOWER = "Jump Power",
		OPT_JUMPVALUE = "Jump Value",
		OPT_FLY = "Fly",
		OPT_FLYSPEED = "Fly Speed",
		OPT_NOCLIP = "Noclip",
		OPT_INFJUMP = "Infinite Jump",
		OPT_SCENEPRESET = "Scene Preset",
		OPT_FULLBRIGHT = "Full Bright",
		OPT_NOSHADOWS = "No Shadows",
		OPT_EXPOSURE = "Exposure Override",
		OPT_EXPOSUREVAL = "Exposure",
		OPT_HIDECLOUDS = "Hide Clouds",
		OPT_GRAVITY = "Gravity Override",
		OPT_GRAVITYVAL = "Gravity",
		OPT_HUD = "HUD",
		OPT_CUSTOMFOV = "Custom FOV",
		OPT_CAMERAFOV = "Camera FOV",
		OPT_HOLDZOOM = "Hold Zoom",
		OPT_ZOOMFOV = "Zoom FOV",
		OPT_FREECAM = "Freecam",
		OPT_FREECAMSPEED = "Freecam Speed",
		OPT_ZOOMLIMIT = "Zoom Out Limit",
		OPT_MAXZOOM = "Max Zoom Distance",
		OPT_SNOW = "Snow",
		OPT_SNOWDENSITY = "Snow Density",
		OPT_RAIN = "Rain",
		OPT_RAINDENSITY = "Rain Density",
		OPT_WIND = "Wind",
		OPT_FOG = "Fog",
		OPT_FOGDIST = "Fog Distance",
		OPT_FOGCOLOR = "Fog Color",
		OPT_LIGHTNING = "Lightning",
		OPT_LIGHTNINGINT = "Lightning Interval",
		OPT_ATMOSPHERE = "Atmosphere",
		OPT_ATMODENSITY = "Atmo Density",
		OPT_ATMOHAZE = "Atmo Haze",
		OPT_ATMOCOLOR = "Atmo Color",
		OPT_SUNRAYS = "Sun Rays",
		OPT_RAYSINT = "Rays Intensity",
		OPT_RAYSSPREAD = "Rays Spread",
		OPT_RAINBOW = "Rainbow World",
		OPT_RAINBOWSPEED = "Rainbow Speed",
		OPT_FORCETIME = "Force Time Of Day",
		OPT_TIMEOFDAY = "Time Of Day",
		OPT_TIMEFLOW = "Time Flow",
		OPT_FLOWSPEED = "Flow Speed",
		OPT_GLOW = "Glow / Bloom",
		OPT_GLOWINT = "Glow Intensity",
		OPT_COLORGRADE = "Color Grading",
		OPT_SATURATION = "Saturation",
		OPT_TINT = "Tint",
		OPT_VISIONMODE = "Vision Mode",
		OPT_DOF = "Depth Of Field",
		OPT_FOCUSDIST = "Focus Distance",
		OPT_BLURAMOUNT = "Blur Amount",
		OPT_FOCUSRADIUS = "Focus Radius",
		OPT_SCREENBLUR = "Screen Blur",
		OPT_BLURSIZE = "Blur Size",
		OPT_VIGNETTE = "Vignette",
		OPT_VIGNETTEINT = "Vignette Strength",
		OPT_CUSTOMCROSS = "Custom Crosshair",
		OPT_CROSSSIZE = "Crosshair Size",
		OPT_CROSSGAP = "Crosshair Gap",
		OPT_CROSSTHICK = "Crosshair Thickness",
		OPT_CENTERDOT = "Center Dot",
		OPT_CROSSCOLOR = "Crosshair Color",
		OPT_SPIN = "Spin",
		OPT_DYNAMICGAP = "Dynamic Gap",
		OPT_REDONTARGET = "Turn Red On Target",
		OPT_HITMARKER = "Hit Marker",
		OPT_HITSOUND = "Hit Sound",
		OPT_THEME = "Theme",
		OPT_ACCENT = "Accent",
		OPT_MENUSCALE = "Menu Scale",
		OPT_MENUTRANSP = "Menu Transparency",
		OPT_LANGUAGE = "Language",
		LBL_USERNAME = "Username",
		LBL_USERID = "User ID",
		LBL_DISPLAYNAME = "Display Name",
		LBL_ACCOUNTAGE = "Account Age",
		LBL_SESSIONTIME = "Session Time",
		LBL_PLACEID = "Place ID",
		LBL_JOBID = "Job ID",
		LBL_PLAYERCOUNT = "Players In Server",
		LBL_PING = "Ping",
		LBL_FPS = "FPS",
		LBL_TEAM = "Team",
		LBL_HEALTH = "Health",
		LBL_CHARSTATE = "Character State",
		LBL_ALIVE = "Alive",
		LBL_DEAD = "Dead",
		LBL_NOCHAR = "No Character",
		LBL_NOTEAM = "None",
		LBL_DAYS = "days",
		LBL_CONFIGNAME = "Config name",
		LBL_CONFIGSTRING = "Config string (copy / paste)",
		PH_CONFIGNAME = "e.g. legit, rage, retail",
		PH_CONFIGSTRING = "Paste config here, or press Export",
		BTN_EXPORT = "EXPORT CONFIG",
		BTN_IMPORT = "IMPORT CONFIG",
		BTN_SAVE = "SAVE TO FILE",
		BTN_LOAD = "LOAD FROM FILE",
		BTN_REFRESH = "REFRESH LIST",
		BTN_RESET = "RESET TO DEFAULTS",
		BTN_UNLOAD = "UNLOAD SCRIPT",
		BTN_RESETCOLORS = "RESET COLORS",
		LBL_SAVEDCONFIGS = "Saved configs",
		TOAST_LOADED = "Vortex loaded",
		TOAST_PRESET = "Preset: %s",
		TOAST_EXPORTED = "Config exported",
		TOAST_IMPORTED = "Config imported (%d values)",
		TOAST_IMPORTFAIL = "Import failed or empty",
		TOAST_DEFAULTS = "Defaults restored",
		TOAST_SAVED = "Saved to VortexCheats/%s.cfg",
		TOAST_SAVEFAIL = "Save failed, check name",
		TOAST_LOADED_FILE = "Loaded %s (%d values)",
		TOAST_LOADFAIL = "File not found",
		TOAST_LANGSET = "Language set: %s",
		TOAST_NOFOLDER = "No saved configs yet",
		BIND_MENU = "Menu",
		BIND_ZOOM = "Zoom (hold)",
	},
	UA = {
		APP_NAME = "VORTEX",
		APP_SUB = "БОЙОВИЙ ХАБ",
		TAB_AIMBOT = "АЙМБОТ",
		TAB_VISUALS = "ВІЗУАЛ",
		TAB_MOVEMENT = "РУХ",
		TAB_WORLD = "СВІТ",
		TAB_PROFILE = "ПРОФІЛЬ",
		TAB_BINDS = "КЛАВІШІ",
		TAB_SETTINGS = "НАЛАШТУВАННЯ",
		MENU_KEY = "КЛАВІША МЕНЮ",
		SEC_AIMBOT = "АЙМБОТ",
		SEC_TRIGGER = "ТРИГЕР БОТ",
		SEC_ESP = "ESP",
		SEC_MOVEMENT = "РУХ",
		SEC_PRESETS = "ПРЕСЕТИ",
		SEC_RENDERING = "РЕНДЕРИНГ",
		SEC_CAMERA = "КАМЕРА",
		SEC_WEATHER = "ПОГОДА",
		SEC_ATMOSPHERE = "АТМОСФЕРА",
		SEC_TIME = "ЧАС",
		SEC_POSTFX = "ПОСТ ЕФЕКТИ",
		SEC_CROSSHAIR = "ПРИЦІЛ",
		SEC_HITFX = "ВІДГУК ПОПАДАННЯ",
		SEC_SESSION = "СЕСІЯ",
		SEC_ACCOUNT = "АКАУНТ",
		SEC_SERVER = "СЕРВЕР",
		SEC_INTERFACE = "ІНТЕРФЕЙС",
		SEC_THEME = "КАСТОМІЗАЦІЯ ТЕМИ",
		SEC_CONFIG = "КОНФІГ",
		SEC_SCRIPT = "СКРИПТ",
		SEC_LANGUAGE = "МОВА",
		OPT_AIMBOT = "Аймбот",
		OPT_HOLD_RMB = "Утримувати ПКМ",
		OPT_TEAMCHECK = "Перевірка команди",
		OPT_VISIBLECHECK = "Перевірка видимості",
		OPT_AIMPART = "Частина прицілу",
		OPT_AIMSPEED = "Швидкість прицілу",
		OPT_FOVRADIUS = "Радіус FOV",
		OPT_MAXDIST = "Макс. дистанція",
		OPT_PREDICTION = "Прогноз руху",
		OPT_PREDICTIONTIME = "Час прогнозу",
		OPT_SHOWFOV = "Показати коло FOV",
		OPT_TARGETLINE = "Лінія до цілі",
		OPT_TRIGGERBOT = "Тригер бот",
		OPT_TRIGGERFOV = "FOV тригера",
		OPT_SHOWTRIGGERFOV = "Показати FOV тригера",
		OPT_HITBOX = "Врахувати хітбокс",
		OPT_TRIGGERPART = "Частина тригера",
		OPT_WALLCHECK = "Перевірка стін",
		OPT_ONLYAIM = "Лише під час прицілювання",
		OPT_REACTDELAY = "Затримка реакції",
		OPT_FIREINTERVAL = "Інтервал вогню",
		OPT_HUMANIZE = "Гуманізація таймінгу",
		OPT_CLICKMODE = "Режим кліку",
		OPT_ESP = "ESP",
		OPT_HIDETEAM = "Приховати команду",
		OPT_BOXES = "Рамки",
		OPT_CORNERBOXES = "Кутові рамки",
		OPT_NAMES = "Імена",
		OPT_DISTANCE = "Дистанція",
		OPT_HEALTHBAR = "Смуга здоров'я",
		OPT_SKELETON = "Скелет",
		OPT_HEADDOT = "Точка на голові",
		OPT_WEAPON = "Зброя",
		OPT_OFFSCREEN = "Стрілки поза екраном",
		OPT_CHAMS = "Чамс",
		OPT_TRACERS = "Трасери",
		OPT_TRACERORIGIN = "Початок трасера",
		OPT_ESPCOLOR = "Колір ESP",
		OPT_ESPDIST = "Дистанція ESP",
		OPT_SPEED = "Швидкість",
		OPT_WALKSPEED = "Швидкість ходьби",
		OPT_JUMPPOWER = "Сила стрибка",
		OPT_JUMPVALUE = "Значення стрибка",
		OPT_FLY = "Політ",
		OPT_FLYSPEED = "Швидкість польоту",
		OPT_NOCLIP = "Ноукліп",
		OPT_INFJUMP = "Нескінченний стрибок",
		OPT_SCENEPRESET = "Пресет сцени",
		OPT_FULLBRIGHT = "Повна яскравість",
		OPT_NOSHADOWS = "Без тіней",
		OPT_EXPOSURE = "Перекрити експозицію",
		OPT_EXPOSUREVAL = "Експозиція",
		OPT_HIDECLOUDS = "Приховати хмари",
		OPT_GRAVITY = "Перекрити гравітацію",
		OPT_GRAVITYVAL = "Гравітація",
		OPT_HUD = "HUD",
		OPT_CUSTOMFOV = "Власний FOV",
		OPT_CAMERAFOV = "FOV камери",
		OPT_HOLDZOOM = "Утримувати зум",
		OPT_ZOOMFOV = "FOV зуму",
		OPT_FREECAM = "Вільна камера",
		OPT_FREECAMSPEED = "Швидкість камери",
		OPT_ZOOMLIMIT = "Ліміт віддалення",
		OPT_MAXZOOM = "Макс. дистанція зуму",
		OPT_SNOW = "Сніг",
		OPT_SNOWDENSITY = "Густота снігу",
		OPT_RAIN = "Дощ",
		OPT_RAINDENSITY = "Густота дощу",
		OPT_WIND = "Вітер",
		OPT_FOG = "Туман",
		OPT_FOGDIST = "Дистанція туману",
		OPT_FOGCOLOR = "Колір туману",
		OPT_LIGHTNING = "Блискавка",
		OPT_LIGHTNINGINT = "Інтервал блискавки",
		OPT_ATMOSPHERE = "Атмосфера",
		OPT_ATMODENSITY = "Густота атмосфери",
		OPT_ATMOHAZE = "Серпанок",
		OPT_ATMOCOLOR = "Колір атмосфери",
		OPT_SUNRAYS = "Промені сонця",
		OPT_RAYSINT = "Інтенсивність променів",
		OPT_RAYSSPREAD = "Розсіювання променів",
		OPT_RAINBOW = "Веселковий світ",
		OPT_RAINBOWSPEED = "Швидкість веселки",
		OPT_FORCETIME = "Фіксувати час доби",
		OPT_TIMEOFDAY = "Час доби",
		OPT_TIMEFLOW = "Плин часу",
		OPT_FLOWSPEED = "Швидкість плину",
		OPT_GLOW = "Світіння / Блум",
		OPT_GLOWINT = "Інтенсивність світіння",
		OPT_COLORGRADE = "Кольорокорекція",
		OPT_SATURATION = "Насиченість",
		OPT_TINT = "Відтінок",
		OPT_VISIONMODE = "Режим зору",
		OPT_DOF = "Глибина різкості",
		OPT_FOCUSDIST = "Дистанція фокусу",
		OPT_BLURAMOUNT = "Сила розмиття",
		OPT_FOCUSRADIUS = "Радіус фокусу",
		OPT_SCREENBLUR = "Розмиття екрану",
		OPT_BLURSIZE = "Розмір розмиття",
		OPT_VIGNETTE = "Віньєтка",
		OPT_VIGNETTEINT = "Сила віньєтки",
		OPT_CUSTOMCROSS = "Власний приціл",
		OPT_CROSSSIZE = "Розмір прицілу",
		OPT_CROSSGAP = "Проміжок прицілу",
		OPT_CROSSTHICK = "Товщина прицілу",
		OPT_CENTERDOT = "Центральна точка",
		OPT_CROSSCOLOR = "Колір прицілу",
		OPT_SPIN = "Обертання",
		OPT_DYNAMICGAP = "Динамічний проміжок",
		OPT_REDONTARGET = "Червоний по цілі",
		OPT_HITMARKER = "Маркер попадання",
		OPT_HITSOUND = "Звук попадання",
		OPT_THEME = "Тема",
		OPT_ACCENT = "Акцент",
		OPT_MENUSCALE = "Масштаб меню",
		OPT_MENUTRANSP = "Прозорість меню",
		OPT_LANGUAGE = "Мова",
		LBL_USERNAME = "Ім'я користувача",
		LBL_USERID = "ID користувача",
		LBL_DISPLAYNAME = "Відображуване ім'я",
		LBL_ACCOUNTAGE = "Вік акаунту",
		LBL_SESSIONTIME = "Час сесії",
		LBL_PLACEID = "ID місця",
		LBL_JOBID = "ID сервера",
		LBL_PLAYERCOUNT = "Гравців на сервері",
		LBL_PING = "Пінг",
		LBL_FPS = "ФПС",
		LBL_TEAM = "Команда",
		LBL_HEALTH = "Здоров'я",
		LBL_CHARSTATE = "Стан персонажа",
		LBL_ALIVE = "Живий",
		LBL_DEAD = "Мертвий",
		LBL_NOCHAR = "Немає персонажа",
		LBL_NOTEAM = "Немає",
		LBL_DAYS = "днів",
		LBL_CONFIGNAME = "Назва конфігу",
		LBL_CONFIGSTRING = "Рядок конфігу (копіювати / вставити)",
		PH_CONFIGNAME = "напр. legit, rage, retail",
		PH_CONFIGSTRING = "Вставте конфіг сюди, або натисніть Експорт",
		BTN_EXPORT = "ЕКСПОРТ КОНФІГУ",
		BTN_IMPORT = "ІМПОРТ КОНФІГУ",
		BTN_SAVE = "ЗБЕРЕГТИ У ФАЙЛ",
		BTN_LOAD = "ЗАВАНТАЖИТИ З ФАЙЛУ",
		BTN_REFRESH = "ОНОВИТИ СПИСОК",
		BTN_RESET = "СКИНУТИ ДО ЗАМОВЧУВАННЯ",
		BTN_UNLOAD = "ВИВАНТАЖИТИ СКРИПТ",
		BTN_RESETCOLORS = "СКИНУТИ КОЛЬОРИ",
		LBL_SAVEDCONFIGS = "Збережені конфіги",
		TOAST_LOADED = "Vortex завантажено",
		TOAST_PRESET = "Пресет: %s",
		TOAST_EXPORTED = "Конфіг експортовано",
		TOAST_IMPORTED = "Конфіг імпортовано (%d значень)",
		TOAST_IMPORTFAIL = "Помилка імпорту або пусто",
		TOAST_DEFAULTS = "Замовчування відновлено",
		TOAST_SAVED = "Збережено у VortexCheats/%s.cfg",
		TOAST_SAVEFAIL = "Помилка збереження, перевірте назву",
		TOAST_LOADED_FILE = "Завантажено %s (%d значень)",
		TOAST_LOADFAIL = "Файл не знайдено",
		TOAST_LANGSET = "Мову встановлено: %s",
		TOAST_NOFOLDER = "Ще немає збережених конфігів",
		BIND_MENU = "Меню",
		BIND_ZOOM = "Зум (утримувати)",
	},
	RU = {
		APP_NAME = "VORTEX",
		APP_SUB = "БОЕВОЙ ХАБ",
		TAB_AIMBOT = "АИМБОТ",
		TAB_VISUALS = "ВИЗУАЛ",
		TAB_MOVEMENT = "ДВИЖЕНИЕ",
		TAB_WORLD = "МИР",
		TAB_PROFILE = "ПРОФИЛЬ",
		TAB_BINDS = "КЛАВИШИ",
		TAB_SETTINGS = "НАСТРОЙКИ",
		MENU_KEY = "КЛАВИША МЕНЮ",
		SEC_AIMBOT = "АИМБОТ",
		SEC_TRIGGER = "ТРИГГЕР БОТ",
		SEC_ESP = "ESP",
		SEC_MOVEMENT = "ДВИЖЕНИЕ",
		SEC_PRESETS = "ПРЕСЕТЫ",
		SEC_RENDERING = "РЕНДЕРИНГ",
		SEC_CAMERA = "КАМЕРА",
		SEC_WEATHER = "ПОГОДА",
		SEC_ATMOSPHERE = "АТМОСФЕРА",
		SEC_TIME = "ВРЕМЯ",
		SEC_POSTFX = "ПОСТ ЭФФЕКТЫ",
		SEC_CROSSHAIR = "ПРИЦЕЛ",
		SEC_HITFX = "ОТКЛИК ПОПАДАНИЯ",
		SEC_SESSION = "СЕССИЯ",
		SEC_ACCOUNT = "АККАУНТ",
		SEC_SERVER = "СЕРВЕР",
		SEC_INTERFACE = "ИНТЕРФЕЙС",
		SEC_THEME = "КАСТОМИЗАЦИЯ ТЕМЫ",
		SEC_CONFIG = "КОНФИГ",
		SEC_SCRIPT = "СКРИПТ",
		SEC_LANGUAGE = "ЯЗЫК",
		OPT_AIMBOT = "Аимбот",
		OPT_HOLD_RMB = "Удерживать ПКМ",
		OPT_TEAMCHECK = "Проверка команды",
		OPT_VISIBLECHECK = "Проверка видимости",
		OPT_AIMPART = "Часть прицела",
		OPT_AIMSPEED = "Скорость прицела",
		OPT_FOVRADIUS = "Радиус FOV",
		OPT_MAXDIST = "Макс. дистанция",
		OPT_PREDICTION = "Прогноз движения",
		OPT_PREDICTIONTIME = "Время прогноза",
		OPT_SHOWFOV = "Показать круг FOV",
		OPT_TARGETLINE = "Линия к цели",
		OPT_TRIGGERBOT = "Триггер бот",
		OPT_TRIGGERFOV = "FOV триггера",
		OPT_SHOWTRIGGERFOV = "Показать FOV триггера",
		OPT_HITBOX = "Учитывать хитбокс",
		OPT_TRIGGERPART = "Часть триггера",
		OPT_WALLCHECK = "Проверка стен",
		OPT_ONLYAIM = "Только при прицеливании",
		OPT_REACTDELAY = "Задержка реакции",
		OPT_FIREINTERVAL = "Интервал огня",
		OPT_HUMANIZE = "Гуманизация тайминга",
		OPT_CLICKMODE = "Режим клика",
		OPT_ESP = "ESP",
		OPT_HIDETEAM = "Скрыть команду",
		OPT_BOXES = "Рамки",
		OPT_CORNERBOXES = "Угловые рамки",
		OPT_NAMES = "Имена",
		OPT_DISTANCE = "Дистанция",
		OPT_HEALTHBAR = "Полоса здоровья",
		OPT_SKELETON = "Скелет",
		OPT_HEADDOT = "Точка на голове",
		OPT_WEAPON = "Оружие",
		OPT_OFFSCREEN = "Стрелки вне экрана",
		OPT_CHAMS = "Чамс",
		OPT_TRACERS = "Трейсеры",
		OPT_TRACERORIGIN = "Начало трейсера",
		OPT_ESPCOLOR = "Цвет ESP",
		OPT_ESPDIST = "Дистанция ESP",
		OPT_SPEED = "Скорость",
		OPT_WALKSPEED = "Скорость ходьбы",
		OPT_JUMPPOWER = "Сила прыжка",
		OPT_JUMPVALUE = "Значение прыжка",
		OPT_FLY = "Полёт",
		OPT_FLYSPEED = "Скорость полёта",
		OPT_NOCLIP = "Ноуклип",
		OPT_INFJUMP = "Бесконечный прыжок",
		OPT_SCENEPRESET = "Пресет сцены",
		OPT_FULLBRIGHT = "Полная яркость",
		OPT_NOSHADOWS = "Без теней",
		OPT_EXPOSURE = "Переопределить экспозицию",
		OPT_EXPOSUREVAL = "Экспозиция",
		OPT_HIDECLOUDS = "Скрыть облака",
		OPT_GRAVITY = "Переопределить гравитацию",
		OPT_GRAVITYVAL = "Гравитация",
		OPT_HUD = "HUD",
		OPT_CUSTOMFOV = "Свой FOV",
		OPT_CAMERAFOV = "FOV камеры",
		OPT_HOLDZOOM = "Удерживать зум",
		OPT_ZOOMFOV = "FOV зума",
		OPT_FREECAM = "Свободная камера",
		OPT_FREECAMSPEED = "Скорость камеры",
		OPT_ZOOMLIMIT = "Лимит отдаления",
		OPT_MAXZOOM = "Макс. дистанция зума",
		OPT_SNOW = "Снег",
		OPT_SNOWDENSITY = "Плотность снега",
		OPT_RAIN = "Дождь",
		OPT_RAINDENSITY = "Плотность дождя",
		OPT_WIND = "Ветер",
		OPT_FOG = "Туман",
		OPT_FOGDIST = "Дистанция тумана",
		OPT_FOGCOLOR = "Цвет тумана",
		OPT_LIGHTNING = "Молния",
		OPT_LIGHTNINGINT = "Интервал молнии",
		OPT_ATMOSPHERE = "Атмосфера",
		OPT_ATMODENSITY = "Плотность атмосферы",
		OPT_ATMOHAZE = "Дымка",
		OPT_ATMOCOLOR = "Цвет атмосферы",
		OPT_SUNRAYS = "Лучи солнца",
		OPT_RAYSINT = "Интенсивность лучей",
		OPT_RAYSSPREAD = "Рассеивание лучей",
		OPT_RAINBOW = "Радужный мир",
		OPT_RAINBOWSPEED = "Скорость радуги",
		OPT_FORCETIME = "Зафиксировать время суток",
		OPT_TIMEOFDAY = "Время суток",
		OPT_TIMEFLOW = "Течение времени",
		OPT_FLOWSPEED = "Скорость течения",
		OPT_GLOW = "Свечение / Блум",
		OPT_GLOWINT = "Интенсивность свечения",
		OPT_COLORGRADE = "Цветокоррекция",
		OPT_SATURATION = "Насыщенность",
		OPT_TINT = "Оттенок",
		OPT_VISIONMODE = "Режим зрения",
		OPT_DOF = "Глубина резкости",
		OPT_FOCUSDIST = "Дистанция фокуса",
		OPT_BLURAMOUNT = "Сила размытия",
		OPT_FOCUSRADIUS = "Радиус фокуса",
		OPT_SCREENBLUR = "Размытие экрана",
		OPT_BLURSIZE = "Размер размытия",
		OPT_VIGNETTE = "Виньетка",
		OPT_VIGNETTEINT = "Сила виньетки",
		OPT_CUSTOMCROSS = "Свой прицел",
		OPT_CROSSSIZE = "Размер прицела",
		OPT_CROSSGAP = "Промежуток прицела",
		OPT_CROSSTHICK = "Толщина прицела",
		OPT_CENTERDOT = "Центральная точка",
		OPT_CROSSCOLOR = "Цвет прицела",
		OPT_SPIN = "Вращение",
		OPT_DYNAMICGAP = "Динамический промежуток",
		OPT_REDONTARGET = "Красный по цели",
		OPT_HITMARKER = "Маркер попадания",
		OPT_HITSOUND = "Звук попадания",
		OPT_THEME = "Тема",
		OPT_ACCENT = "Акцент",
		OPT_MENUSCALE = "Масштаб меню",
		OPT_MENUTRANSP = "Прозрачность меню",
		OPT_LANGUAGE = "Язык",
		LBL_USERNAME = "Имя пользователя",
		LBL_USERID = "ID пользователя",
		LBL_DISPLAYNAME = "Отображаемое имя",
		LBL_ACCOUNTAGE = "Возраст аккаунта",
		LBL_SESSIONTIME = "Время сессии",
		LBL_PLACEID = "ID места",
		LBL_JOBID = "ID сервера",
		LBL_PLAYERCOUNT = "Игроков на сервере",
		LBL_PING = "Пинг",
		LBL_FPS = "ФПС",
		LBL_TEAM = "Команда",
		LBL_HEALTH = "Здоровье",
		LBL_CHARSTATE = "Состояние персонажа",
		LBL_ALIVE = "Жив",
		LBL_DEAD = "Мёртв",
		LBL_NOCHAR = "Нет персонажа",
		LBL_NOTEAM = "Нет",
		LBL_DAYS = "дней",
		LBL_CONFIGNAME = "Название конфига",
		LBL_CONFIGSTRING = "Строка конфига (копировать / вставить)",
		PH_CONFIGNAME = "напр. legit, rage, retail",
		PH_CONFIGSTRING = "Вставьте конфиг сюда, или нажмите Экспорт",
		BTN_EXPORT = "ЭКСПОРТ КОНФИГА",
		BTN_IMPORT = "ИМПОРТ КОНФИГА",
		BTN_SAVE = "СОХРАНИТЬ В ФАЙЛ",
		BTN_LOAD = "ЗАГРУЗИТЬ ИЗ ФАЙЛА",
		BTN_REFRESH = "ОБНОВИТЬ СПИСОК",
		BTN_RESET = "СБРОСИТЬ ПО УМОЛЧАНИЮ",
		BTN_UNLOAD = "ВЫГРУЗИТЬ СКРИПТ",
		BTN_RESETCOLORS = "СБРОСИТЬ ЦВЕТА",
		LBL_SAVEDCONFIGS = "Сохранённые конфиги",
		TOAST_LOADED = "Vortex загружен",
		TOAST_PRESET = "Пресет: %s",
		TOAST_EXPORTED = "Конфиг экспортирован",
		TOAST_IMPORTED = "Конфиг импортирован (%d значений)",
		TOAST_IMPORTFAIL = "Ошибка импорта или пусто",
		TOAST_DEFAULTS = "Настройки по умолчанию восстановлены",
		TOAST_SAVED = "Сохранено в VortexCheats/%s.cfg",
		TOAST_SAVEFAIL = "Ошибка сохранения, проверьте имя",
		TOAST_LOADED_FILE = "Загружено %s (%d значений)",
		TOAST_LOADFAIL = "Файл не найден",
		TOAST_LANGSET = "Язык установлен: %s",
		TOAST_NOFOLDER = "Пока нет сохранённых конфигов",
		BIND_MENU = "Меню",
		BIND_ZOOM = "Зум (удержание)",
	},
}

Locale.Registry = {}
Locale.Listeners = {}
Locale.Pending = false

function Locale.T(key)
	local set = Locale.Strings[Locale.Current] or Locale.Strings.EN
	return set[key] or Locale.Strings.EN[key] or key
end

function Locale.Bind(instance, key, property, formatArgs)
	property = property or "Text"
	table.insert(Locale.Registry, {
		Instance = instance,
		Key = key,
		Property = property,
		Args = formatArgs,
	})
	local ok = pcall(function()
		if formatArgs then
			instance[property] = string.format(Locale.T(key), table.unpack(formatArgs))
		else
			instance[property] = Locale.T(key)
		end
	end)
	if not ok then
		instance[property] = Locale.T(key)
	end
end

function Locale.OnChange(callback)
	table.insert(Locale.Listeners, callback)
end

local function ApplyNow()
	for index = #Locale.Registry, 1, -1 do
		local entry = Locale.Registry[index]
		if not entry.Instance or entry.Instance.Parent == nil then
			table.remove(Locale.Registry, index)
		else
			local text = Locale.T(entry.Key)
			if entry.Args then
				local ok, formatted = pcall(string.format, text, table.unpack(entry.Args))
				if ok then
					text = formatted
				end
			end
			entry.Instance[entry.Property] = text
		end
	end
	for _, callback in ipairs(Locale.Listeners) do
		task.spawn(callback)
	end
end

function Locale.SetLanguage(code, notifyFn)
	if Locale.Strings[code] == nil then
		return false
	end
	if Locale.Pending then
		return false
	end
	Locale.Pending = true
	task.delay(2, function()
		Locale.Current = code
		ApplyNow()
		Locale.Pending = false
		if notifyFn then
			notifyFn(string.format(Locale.T("TOAST_LANGSET"), code))
		end
	end)
	return true
end

function Locale.SetImmediate(code)
	if Locale.Strings[code] == nil then
		return false
	end
	Locale.Current = code
	ApplyNow()
	return true
end

return Locale